// This file generated by CppReflection.ClassExpoter.
#include "pch.h"
#include "DynamicType.hpp"

#include "../App/IApplicationComponent.hpp"
#include "../App/Components/FpsController.hpp"
#include "../App/Components/Resources/Resources.hpp"
#include "../App/Components/Random.hpp"

using namespace Egliss::Reflection;
using namespace std::string_literals;

std::vector<DynamicTypeDescription> DynamicTypeManager::_indexedTypes;
std::unordered_map<std::string, int> DynamicTypeManager::_typesindices;


void DynamicTypeManager::Initialize()
{
	_indexedTypes.emplace_back("Egliss::IApplicationComponent", true,std::vector<int>({0}),[](){return nullptr; });
	_typesindices.emplace("Egliss::IApplicationComponent"s, 0);
	_indexedTypes.emplace_back("Egliss::FpsController", false,std::vector<int>({1 ,0}),[](){return new Egliss::FpsController(); });
	_typesindices.emplace("Egliss::FpsController"s, 1);
	_indexedTypes.emplace_back("Egliss::Resources", false,std::vector<int>({2 ,0}),[](){return new Egliss::Resources(); });
	_typesindices.emplace("Egliss::Resources"s, 2);
	_indexedTypes.emplace_back("Egliss::Random", false,std::vector<int>({3 ,0}),[](){return new Egliss::Random(); });
	_typesindices.emplace("Egliss::Random"s, 3);
}
