// This file generated by CppReflection.ClassExpoter.
#include "DynamicType.hpp"

using namespace Egliss::Reflection;
using namespace std::string_literals;

std::vector<DynamicTypeDescription> DynamicTypeManager::_indexedTypes;
std::unordered_map<std::string, int> DynamicTypeManager::_typesindices;


void Egliss::Reflection::DynamicTypeManager::Initialize()
{
}
